[build]
  command = "php -S localhost:8000 & sleep 5 && php build.php"
  publish = "dist"

[build.environment]
  PHP_VERSION = "8.2"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[dev]
  command = "php -S localhost:8000"
  port = 8000
  publish = "dist"
